version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  server:
    build:
      context: ./buildlog_server
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 5000 -b '0.0.0.0'"
    volumes:
      - ./buildlog_server/:/server
    ports:
      - "5000:5000"
    depends_on:
      - db
  client:
    build:
      context: ./buildlog_client
      dockerfile: Dockerfile
    volumes:
      - ./buildlog_client/:/app
    ports:
      - 3000:3000